BASE_PATH_TOOL_1 = "corpusfiles/processing/pipeline_stage_1/"
BASE_PATH_MT = "corpusfiles/processing/pipeline_stage_2/"
BASE_PATH_TOOL_3 = "corpusfiles/processing/pipeline_stage_3/"

ERROR_TOPIC = 'toolerror'
EXTRACTOR_RESPONSE = 'tokenprocessed'

SESSION_ID = 'session_id'
DATA = 'data'
TITLE = 'title'

CSV_RT = 'rt'
CSV_WRITE = 'w'
CSV_APPEND = 'a'

CONFIG_NAME = 'config_name'
SFILE_HEADER = 'specific_file_header'
SEC = 'sentence_end_characters'
REGEX_RULES = 'regex_rules_for_token_extraction'
TOKEN_LENGTH_MAX = 'token_length_max'
TOKEN_LENGTH_MIN = 'token_length_min'
USE_TOKENS_FROM_DB = 'use_tokens_from_db'
REMOVE_NEGATIVE_TOKEN = 'remove_negative_tokens'
ADD_NEGATIVE_TOKENS = 'add_negative_tokens'
TOKEN_INSERTION_ORDER = 'token_insertion_order'
CONFIG_FILE_LOCATION = 'config_file_location'
TOKEN_FILE = 'token_file'
NEGATIVE_TOKEN_FILE = 'negative_token_file'
PARAGRAPH_FILE_LOCATION = 'paragraph_file_location'
SENTENCES = 'sentences'
NEGATIVE_TOKEN_FILE_PATH = 'resources/negative_tokens.csv'
EXCLUSIVE_TOKENS = 'exclusive_tokens'
MIN_SEN_LENGTH = 'min_sentence_length'

SOURCE_FILES = 'source_files'
TARGET_LANGUAGE = 'target_language'
SOURCE_LANGUAGE = 'source_language'
TARGET_LANGUAGES = 'target_languages'
STATUS = 'status'
FILES = 'files'
INDEX = 'index'
FILE_COUNT = 'file_count'

SOURCE_LANG = 'source_lang'
DOCUMENT_TITLE = 'document_title'
DOMAIN = 'domain'
CREATED_DATE = 'created_date'
UPDATED_DATE = 'update_date'
CREATED_BY = 'created_by'
UPDATED_BY = 'update_by'
PROCESS_ID = 'process_id'
SOURCE_SENTENCE = 'source_sentence'
TARGET_SENTENCES = 'target_sentences'
TARGET_SENTENCE = 'target_sentence'

SENTENCES_INDEX = 'sentences'
HASH = 'hash'
ID = '_id'
DOCS = 'docs'
FOUND = 'found'
_SOURCE = '_source'

ENGLISH = 'english'
IS_COMPLETE = 'is_complete'
COMPLETE = 'complete'
BATCH_SIZE = 25
HASHES = 'hashes'
TOPIC_SENTENCES_PROCESSING = 'sentenceprocessing'
FILE_NAME = 'file_name'
TYPE = 'type'
WRITE_CSV = 'write_csv'
USE_LATEST = 'use_latest'
TRANSLATE = 'translate'
TOPIC_FETCHER = 'fetcher'
TOPIC_MACHINE_TRANSLATION = 'sentencesmt'
TOPIC_MT_RESPONSE = 'mtresponse'

DEFAULT_WAIT_TIME = 5
SOURCE = 'source'
TARGET = 'target'
RESULT = 'result'
PATH = 'path'
FAILED = 'FAILED'
SUCCESS = 'success'
SELECTED_FILES = 'selected_files'
_HASH = '_hash'

FILE_INDEX = 'file_index'


TOPIC_SEARCH_REPLACE = 'searchreplace'
SEARCH_REPLACE = 'search_replace'
WRITE_TO_FILE = 'write_to_file'
TRANSLATED = 'translated'
REPLACE = 'replace'
SEARCH_REPLACE_DB = 'preprocessing'
UPDATED = 'updated'
FINAL_CSV = '_final.csv'
SOURCE_TXT = '_source.txt'
TARGET_TXT = '_target.txt'
SOURCE_FILE = 'source_file'
TARGET_FILE = 'target_file'
SENTENCE_COUNT = 'sentence_count'
SENTENCE_COUNT_REJECTED = 'sentence_count_rejected'
REJECTED = 'rejected'
REJECTED_FILE = 'rejected_file'
MT_STATS = 'mt_stats'
ALREADY_PRESENT = 'already_present'
TOTAL = 'total'
TO_FETCH = 'to_fetch'
NOT_SELECTED_CSV = '_not_selected.csv'
USERNAME = 'username'
PROCESSING = 'PROCESSING'
DOMAIN_LC = 'lc'
TOOL_CHAIN = 'TOOL_CHAIN'

